### ISSUE TITLE
Change summary plot at end of notebook 0

### ISSUE THREAD

**Issue by KateKraft** [KwatME/find_differential_expression#2]
I have 64 samples, and there are not enough colors to plot them all. So we should either find a way to plot that many samples, or plot something else, or plot nothing at all.

<img width="777" alt="screen shot 2018-10-12 at 16 03 22" src="https://user-images.githubusercontent.com/20215501/46897591-6b63e780-ce38-11e8-8dcb-64e8119824a8.png">

**Comment by KateKraft** [comment]
Options to fix this:

1) increase number of colors to unlimited somehow.

2) add logic that says if number of columns is greater than x: just plot the values as one distribution, instead of separate distributions foe each sample.

**Comment by KwatME** [comment]
Got it :) And done :)
