### ISSUE TITLE
Output directory structure and naming

### ISSUE THREAD

**Issue by KateKraft** [KwatME/find_differential_expression#8]
We should enable something like this where the last word added is the name of the function used:

<img width="305" alt="screen shot 2018-10-17 at 12 58 29" src="https://user-images.githubusercontent.com/20215501/47112936-8e154800-d20c-11e8-954e-9035ba1537b6.png">

Also, "All **Genes**" and "**Gene** to Peek" are inconsistent. We should use "Genes" in both or "Gene" in both.

**Comment by KwatME** [comment]
IC will be saved in a directory and the result from looking at the ratio will be saved in another directory.

![screenshot from 2018-10-23 18-41-25](https://user-images.githubusercontent.com/7741548/47400764-887b9e80-d6f3-11e8-9d58-d61bfaede26c.png)

![screenshot from 2018-10-23 18-41-31](https://user-images.githubusercontent.com/7741548/47400768-8addf880-d6f3-11e8-95ea-a873d18dc54a.png)

**Comment by KateKraft** [comment]
Okay, that works too
